name: Release new build on prod pod

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  release_new_build:
    runs-on:
      - self-hosted
      - main

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present